const fakeDataDetails = [
    {
        "id": 1,
        "place": "cox's bazar",
        "img": "https://i.ibb.co/xf7S9Vw/Rectangle-26.png",
        "title": "Light bright airy apt & safe peaceful stay",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.6(10)",
        "nightprice": 34,
    },
    {
        "id": 2,
        "place": "cox's bazar",
        "img": "https://i.ibb.co/fFcgyMT/Rectangle-27.png",
        "title": "Apartment in lost panaorama",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.8(12)",
        "nightprice": 52,
    },
    {
        "id": 3,
        "place": "cox's bazar",
        "img": "https://i.ibb.co/n0vRn88/Rectangle-28.png",
        "title": "AR Lounge & Pool(r&r + b&b",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.9(20)",
        "nightprice": 42,
    },
    {
        "id": 4,
        "place": "srimangal",
        "img": "https://i.ibb.co/xf7S9Vw/Rectangle-26.png",
        "title": "Light bright airy apt & safe peaceful stay",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.6(21)",
        "nightprice": 34,
    },
    {
        "id": 5,
        "place": "srimangal",
        "img": "https://i.ibb.co/fFcgyMT/Rectangle-27.png",
        "title": "Apartment in lost panaorama",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.8(25)",
        "nightprice": 52,
    },
    {
        "id": 6,
        "place": "srimangal",
        "img": "https://i.ibb.co/n0vRn88/Rectangle-28.png",
        "title": "AR Lounge & Pool(r&r + b&b",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.9(24)",
        "nightprice": 42,
    },
    {
        "id": 7,
        "place": "sundarban",
        "img": "https://i.ibb.co/xf7S9Vw/Rectangle-26.png",
        "title": "Light bright airy apt & safe peaceful stay",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.6(21)",
        "nightprice": 34,
    },
    {
        "id": 8,
        "place": "sundarban",
        "img": "https://i.ibb.co/fFcgyMT/Rectangle-27.png",
        "title": "Apartment in lost panaorama",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.8(25)",
        "nightprice": 52,
    },
    {
        "id": 9,
        "place": "sundarban",
        "img": "https://i.ibb.co/n0vRn88/Rectangle-28.png",
        "title": "AR Lounge & Pool(r&r + b&b",
        "guests": 4,
        "bed": 2,
        "bath": 2,
        "facilities": "Wif air conditioning kithcen cancellation fexibility available",
        "star": "https://i.ibb.co/gtM8D3X/star-1.png",
        "rate": "4.9(24)",
        "nightprice": 42,
    }
];

export default fakeDataDetails;